[project]
name = "laboratorio2-ia"
version = "0.1.0"
description = ""
authors = [
    {name = "Sebastian",email = "srojaslo3@ucvvirtual.edu.pe"}
]
requires-python = ">=3.12"
dependencies = [
    "opencv-python (>=5.0.0.93,<6.0.0.0)",
    "numpy (>=2.5.3,<3.0.0)",
    "matplotlib (>=3.11.1,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
